### ISSUE TITLE
2.1.0 OAuth2Client java调用报错

### ISSUE THREAD

**Issue by hibigbo** [ECNU/ecnu-openapi-sdk-java#8]
![1](https://github.com/ECNU/ecnu-openapi-sdk-java/assets/86349053/7a7b60ab-49f0-47e9-add2-daf7d26fd481)
调用时上图标记行报错，报错信息见附件。
[新建文本文档.txt](https://github.com/ECNU/ecnu-openapi-sdk-java/files/15315362/default.txt)

**Comment by szhgoldeneye** [comment]
@hibigbo 你的问题初步判断可能是依赖版本冲突
如果你是基于maven搭建的项目，可以使用`mvn dependency:tree`
如果你是gradle的项目，可以使用`gradle dependencies`
如项目readme中提到的，jackson的版本是jackson 2.13.0，可以从这下手排查一下问题

**Comment by hibigbo** [comment]
@szhgoldeneye 
![2](https://github.com/ECNU/ecnu-openapi-sdk-java/assets/86349053/a076050e-51e1-4679-915f-b5a38a6f5691)
图中标记是我们项目使用的jackson 版本，其余是本次依赖包，请问这种要如何处理？

**Comment by szhgoldeneye** [comment]
@hibigbo 可能发现打包上传仓库里依赖有点问题，您可以尝试使用
```
        <dependency>
            <groupId>io.github.ecnu</groupId>
            <artifactId>ecnu-openapi-sdk-java</artifactId>
            <version>2.1.1-RELEASE</version>
        </dependency>
```
2.1.1版本，如有问题可以及时联系

**Comment by hibigbo** [comment]
@szhgoldeneye 不行哎，还是这个错。

**Comment by szhgoldeneye** [comment]
如果你是在用maven管理项目，可以尝试在pom.xml中加入
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>2.13.0</version> <!-- 请使用最新的稳定版本 -->
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.13.0</version> <!-- 请使用最新的稳定版本 -->
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.datatype</groupId>
                <artifactId>jackson-datatype-jsr310</artifactId>
                <version>2.13.0</version> <!-- 请使用最新的稳定版本 -->
            </dependency>
        </dependencies>
    </dependencyManagement>
```
固定使用版本

**Comment by hibigbo** [comment]
@szhgoldeneye 引用了，还是不行，同样的报错。

**Comment by szhgoldeneye** [comment]
@hibigbo 能否将你的pom文件提供出来，我这边模拟下看看问题

**Comment by hibigbo** [comment]
@szhgoldeneye 这恐怕不太行...不过我们这使用的jackson相关的就只有上面发的那两个。

**Comment by szhgoldeneye** [comment]
@hibigbo 你图上的jackson-all-2.0.1.jar这个我没有在网络上找到，不知道你这边是从哪来的包，是否可以提供来源地址
